- name: Restart Redis
  systemd:
    name: "{{ redis_instance_service }}"
    state: restarted

- name: Reload systemd
  systemd:
    daemon_reload: yes


- name: Restart Redis Sentinel
  systemd:
    name: "{{ redis_sentinel_service_name }}"
    state: restarted

