#!/bin/sh
#
# chkconfig: 345 20 80
# description: Redis is an open source (BSD licensed), in-memory data structure store, used as database, cache and message broker.
 
# Source function library.
. /etc/init.d/functions
 

EXEC=/usr/local/bin/redis-server
CLIEXEC=/usr/local/bin/redis-cli
 
PIDFILE=/var/run/redis.pid
CONF="/etc/redis/redis.conf"


redis_start()
{
if [ -f $PIDFILE ]
        then
            echo "$PIDFILE exists, process is already running or crashed"
        else
            echo "Starting Redis server..."
            $EXEC $CONF
        fi

}

redis_stop()
{

        if [ ! -f $PIDFILE ]
        then
            echo "$PIDFILE does not exist, process is not running"
        else
            PID=$(cat $PIDFILE)
            echo "Stopping ..."
            $CLIEXEC  shutdown
            while [ -x /proc/${PID} ]
            do
                echo "Waiting for Redis to shutdown ..."
                sleep 1
            done
            echo "Redis stopped"
        fi



}
 
case "$1" in
    start)
        redis_start
        ;;
    stop)
        redis_stop
        ;;
    restart)
        redis_stop
        redis_start
        ;;
    status)
        status -p $PIDFILE redis
        script_result=$?
        ;;
    *)
        echo "Please use start, stop, restart or status as first argument"
        ;;
esac
exit 0
